### PR TITLE
Sidebar collapse and expand bugfixfix among others

### PR DESCRIPTION
**Pull request by hope-ag**

### CODE REVIEW

**Comment by travailbeyondexcellence** [comment]
I will review and merge the pull request today

**Comment by pewebdevelopment** [comment]
Also, kindly ping me on my Telegram for me to beable to send videos regarding the project

There is no upload size limit on Telgram (upto 4 GB)

My TG is @veryhighonphysics

**Review by travailbeyondexcellence — APPROVED** [review]
Hello, how did you know the products to be entered, in the Stores/main.js that were missing. 

Are the available in some other place in the original VuePremium Repo

**Comment by hope-ag** [comment]
> 

I just went to check what fields were expected in the table component where the data is used, and reverse-create the needed data.

**Comment by hope-ag** [comment]
> Also, kindly ping me on my Telegram for me to beable to send videos regarding the project
> 
> There is no upload size limit on Telgram (upto 4 GB)
> 
> My TG is @veryhighonphysics

Alright, I'll ping you on Telegram

**Pull request merged**
